#networks:
#  dev:

services:
#  backend:
#    build:
#      context: ./backend
#    networks:
#      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - anastasi_nails_default